project_id = "papxwejgalaywhypsdwf"

[functions.ai-chat]
verify_jwt = true

[functions.openai-chat]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
